# Generated by Django 2.0.2 on 2018-06-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180630_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='put_date',
            new_name='pub_date',
        ),
    ]
